version: 1

update_configs:
  - package_manager: "elixir:hex"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"

